#pragma once

#include "IMGUI/imgui.h"

namespace Graphics
{ 
	class GraphicsInterface;
	typedef struct BufferHandle;
	typedef struct GraphicsPipeline;
	namespace Platform
	{
		class BaseWindow;
	}
	namespace UI
	{
		//! This class will process draw lists generated by ImGUI to be processed by 
		//! the current graphics API
		class UIInterface
		{
		public:
			UIInterface();
			~UIInterface();
			bool Initialize(Platform::BaseWindow* window, GraphicsInterface* graphicsInterface);
			void StartFrame();
			void EndFrame();
			void Release();
	
		private:
			void CreateUIResources();
			
			GraphicsInterface* mGraphicsInterface;
			Graphics::Platform::BaseWindow* mOutputWindow;
			BufferHandle mVertexBuffer;
			BufferHandle mIndexBuffer;
			GraphicsPipeline mGraphicsPipeline;
		};
	}
}